version: '3.8'

services:
  backend:
    build:
      context: ./backend 
      dockerfile: Dockerfile
    container_name: backend-app
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    restart: unless-stopped
  frontend:
    build:
      context: ./frontend 
      dockerfile: Dockerfile
    container_name: frontend-app
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
